package GUI;

import JFileChooser.ClaseFrame;
import logica.Grafo;
import logica.ListaDoble;
import logica.Nodo;
import logica.NodoArista;

/**
 * Esta clase crea una ventana donde se mostrará una alerta especial
 * al usuario antes de guardar un Archivo.
 * 
 * @author: Stefano Boschetti
 * @author: Diego De Jesus
 * @version: 20/02/2024
 */
public class AlertaGuardarArchivo extends javax.swing.JFrame {
//    Campos de la clase
    Grafo myGrafo;
    
/**
 * Constructor de la ventana Alerta.
 *
 * @param myG Grafo a guardar en el archivo de texto.
 */
    public AlertaGuardarArchivo(Grafo myG) {
        initComponents();
        this.setAlwaysOnTop(true);
        myGrafo = myG;
    }//Cierre del constructor

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setText("<html>\n\n<p align=\"center\">\nSeleccione el archivo .txt\n</br>\ndonde desea guardar el grafo.\n </p>\n\n</html>");
        msg.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(okBtn)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(okBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Método que al ser activado el botón "okBtn"  cierra esta ventana 
 * y llamá a un JFileChooser para guardar el grafo.
 */
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.dispose();
        String content = "";
        ClaseFrame importWindow = new ClaseFrame();
        importWindow.setAlwaysOnTop(true);
//        Escribimos las ciudades de nuestro archivo.
        content += "ciudad\n";
        for (int i = 0; i < myGrafo.numVertices; i++) {
            content += String.format("%d\n", i);
        }
//        Escribimos las aristas.
        content += "aristas\n";
//        Creamos una lista para guardar las aristas ya almacenadas.
        ListaDoble vertices = new ListaDoble();
        for (int j = 0; j < myGrafo.numVertices; j++) {
            for (NodoArista auxNodo = myGrafo.listaAdy[j].first; auxNodo != null; auxNodo = auxNodo.next) {
                if(!vertices.contains(String.format("%d,%d,%.2f\n", auxNodo.id, j, auxNodo.distancia))){
                    vertices.push(String.format("%d,%d,%.2f\n", j, auxNodo.id, auxNodo.distancia));
                }    
            }
        }
//        Ahora guardamos las aristas no repetidas.
        for (Nodo x = vertices.first; x != null; x = x.next ) {
            content += x.text;
        }
        importWindow.guardarArchivo(content);
    }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}//Cierre de la clase
