/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import logica.Grafo;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;

/**
 *
 * @author necro
 */
public class VentanaInicial extends javax.swing.JFrame {
    Graph graph = new SingleGraph("Ejemplo");
    Grafo myGrafo = new Grafo(20);
    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
//        Se crea nuestro grafo propio
        myGrafo.crearVertice("Caracas");
        myGrafo.crearVertice("Valencia");
        myGrafo.crearVertice("Barquisimeto");
        myGrafo.crearArista(0,1,800);
        myGrafo.crearArista(1,2,400);
//        Se crea el grafo de GraphStream
        System.setProperty("org.graphstream.ui", "swing");
        graph.addNode("(0)Caracas").setAttribute("ui.label", "(0)Caracas");
        graph.addNode("(1)Valencia").setAttribute("ui.label", "(1)Valencia");
        graph.addNode("(2)Barquisimeto").setAttribute("ui.label", "(2)Barquisimeto");
        graph.addEdge("(0)Caracas(1)Valencia", "(0)Caracas", "(1)Valencia").setAttribute("ui.label", "800");
        graph.addEdge("(1)Valencia(2)Barquisimeto", "(1)Valencia", "(2)Barquisimeto").setAttribute("ui.label", "400");
        graph.display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addCityBtn = new javax.swing.JButton();
        addPathBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addCityBtn.setText("Añadir Ciudad");
        addCityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCityBtnActionPerformed(evt);
            }
        });

        addPathBtn.setText("Añadir Camino");
        addPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPathBtn)
                    .addComponent(addCityBtn))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(addCityBtn)
                .addGap(18, 18, 18)
                .addComponent(addPathBtn)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCityBtnActionPerformed
        // TODO add your handling code here:
        AddCiudad addCityWindow = new AddCiudad(graph, myGrafo);
        addCityWindow.setLocationRelativeTo(this);
        addCityWindow.setVisible(true);
    }//GEN-LAST:event_addCityBtnActionPerformed

    private void addPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPathBtnActionPerformed
        // TODO add your handling code here:
        AddCamino addPathWindow = new AddCamino(graph, myGrafo);
        addPathWindow.setLocationRelativeTo(this);
        addPathWindow.setVisible(true);
    }//GEN-LAST:event_addPathBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCityBtn;
    private javax.swing.JButton addPathBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
